---

- name: Install packages
  ansible.builtin.apt:
    name:
      - nginx
      - postgresql-client
      - python3-psycopg2
      - libpq-dev
    state: present
  become: true

- name: Copy new website configuration file
  ansible.builtin.copy:
    src: files/default_one
    dest: /etc/nginx/sites-available
  become: true

- name: Make new website configuration available
  ansible.builtin.file:
    src: /etc/nginx/sites-available/default_one
    dest: /etc/nginx/sites-enabled/default_one
    state: link
  become: true

- name: Remove default website configuration as available
  ansible.builtin.file:
    path: /etc/nginx/sites-enabled/default
    state: absent
  become: true

- name: Copy new index file
  ansible.builtin.copy:
    src: files/index.html
    dest: /var/www/html
  become: true

- name: Copy simple monitoring script
  ansible.builtin.copy:
    src: files/nginx_monitoring.sh
    dest: /usr/local/bin
    mode: "0770"
  become: true

- name: Create a cron job to run the monitoring script
  ansible.builtin.cron:
    name: "check_nginx"
    minute: "*/5"
    job: "/usr/local/bin/nginx_monitoring.sh"
    user: root
  become: true

- name: Get the IP of the database server
  ansible.builtin.set_fact:
    db_ip_address: "{{ hostvars['db_server']['private_ip_address'] }}"
  delegate_to: 'db_server'

- name: Query the database for the quote
  community.postgresql.postgresql_query:
    login_host: "{{ db_ip_address }}"
    login_db: "{{ db_new_database_name }}"
    login_user: "{{ db_new_database_user }}"
    login_password: "{{ vault_db_user_pass }}"
    query: "SELECT phrase FROM {{ db_new_table_name }} LIMIT 1"
  register: quoting

- name: Create quote page from template
  template:
    src: templates/quote.html.j2
    dest: /var/www/html/quote.html
  become: true