- hosts: localhost
  vars:
    ssh_private_key_file: "./ansible_ssh_info"
    
  tasks:
    - name: Decrypt the key
      ansible.builtin.command:
        cmd: "ansible-vault decrypt {{ ssh_private_key_file }} --output /tmp/ansible_deploy_id"
      no_log: true 

- hosts: aws_ec2
  gather_facts: false
  roles:
    - common

- hosts: web
  gather_facts: false
  roles:
    - web    

- hosts: localhost
  tasks:
    - name: Decrypt the key
      ansible.builtin.command:
        cmd: "rm -f /tmp/ansible_deploy_id"
