---

- name: Prepare AWS ssh key
  gather_facts: false
  hosts: localhost
  vars:
    ssh_private_key_file: "./ansible_ssh_info"
  tasks:
    - name: Decrypt the key
      ansible.builtin.copy:
        src: "{{ ssh_private_key_file }}"
        dest: /tmp/ansible_deploy_id
        mode: "0600"
      no_log: true

- name: Run common role
  hosts: aws_ec2
  gather_facts: false
  roles:
    - common

- name: Run db role on database server
  hosts: db
  gather_facts: false
  roles:
    - db  

- name: Run web role on web servers
  hosts: web
  gather_facts: true
  roles:
    - web

- name: Remove the AWS ssh key
  gather_facts: false
  hosts: localhost
  tasks:
    - name: Decrypt the key
      ansible.builtin.command:
        cmd: "rm -f /tmp/ansible_deploy_id"
      register: cmd_output
      changed_when: cmd_output.rc != 0
